<?php
namespace frontend\components;

use yii\base\Widget;
use yii\db\Query;
use yii\helpers\Html;

class QuesWidget extends Widget{

    public $allChapter;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {


    }
}